### ISSUE TITLE
Pods in Crashloop backoff. Unable to access 'path.logs' (/storage/logs)

### ISSUE THREAD

**Issue by wstrange** [lalamove/helm-elasticsearch#22]
Running on minikube 0.24.1, Kube 1.8.4 with RBAC.

ES data and masters fail to come up. Error logs are included below - but this looks like a user ownership / permission issue.   The template sets the file system group to 1000. I assume the docker container elasticsearch user is supposed to have the same group number - but I suspect it is different for some reason? 

```
[2018-01-02T19:58:36,540][WARN ][o.e.b.ElasticsearchUncaughtExceptionHandler] [es-elasticsearch-data-0] uncaught exception in thread [main]
org.elasticsearch.bootstrap.StartupException: java.lang.IllegalStateException: Unable to access 'path.logs' (/storage/logs)
	at org.elasticsearch.bootstrap.Elasticsearch.init(Elasticsearch.java:134) ~[elasticsearch-6.0.1.jar:6.0.1]
	at org.elasticsearch.bootstrap.Elasticsearch.execute(Elasticsearch.java:121) ~[elasticsearch-6.0.1.jar:6.0.1]
	at org.elasticsearch.cli.EnvironmentAwareCommand.execute(EnvironmentAwareCommand.java:69) ~[elasticsearch-6.0.1.jar:6.0.1]
	at org.elasticsearch.cli.Command.mainWithoutErrorHandling(Command.java:134) ~[elasticsearch-6.0.1.jar:6.0.1]
	at org.elasticsearch.cli.Command.main(Command.java:90) ~[elasticsearch-6.0.1.jar:6.0.1]
	at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:92) ~[elasticsearch-6.0.1.jar:6.0.1]
	at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:85) ~[elasticsearch-6.0.1.jar:6.0.1]
Caused by: java.lang.IllegalStateException: Unable to access 'path.logs' (/storage/logs)
	at org.elasticsearch.bootstrap.FilePermissionUtils.addDirectoryPath(FilePermissionUtils.java:70) ~[elasticsearch-6.0.1.jar:6.0.1]
	at org.elasticsearch.bootstrap.Security.addFilePermissions(Security.java:286) ~[elasticsearch-6.0.1.jar:6.0.1]
	at org.elasticsearch.bootstrap.Security.createPermissions(Security.java:248) ~[elasticsearch-6.0.1.jar:6.0.1]
	at org.elasticsearch.bootstrap.Security.configure(Security.java:121) ~[elasticsearch-6.0.1.jar:6.0.1]
	at org.elasticsearch.bootstrap.Bootstrap.setup(Bootstrap.java:207) ~[elasticsearch-6.0.1.jar:6.0.1]
	at org.elasticsearch.bootstrap.Bootstrap.init(Bootstrap.java:322) ~[elasticsearch-6.0.1.jar:6.0.1]
	at org.elasticsearch.bootstrap.Elasticsearch.init(Elasticsearch.java:130) ~[elasticsearch-6.0.1.jar:6.0.1]
	... 6 more
Caused by: java.nio.file.AccessDeniedException: /storage/logs
	at sun.nio.fs.UnixException.translateToIOException(UnixException.java:84) ~[?:1.8.0_151]
	at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:102) ~[?:1.8.0_151]
	at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:107) ~[?:1.8.0_151]
	at sun.nio.fs.UnixFileSystemProvider.createDirectory(UnixFileSystemProvider.java:384) ~[?:1.8.0_151]
	at java.nio.file.Files.createDirectory(Files.java:674) ~[?:1.8.0_151]
	at java.nio.file.Files.createAndCheckIsDirectory(Files.java:781) ~[?:1.8.0_151]
	at java.nio.file.Files.createDirectories(Files.java:767) ~[?:1.8.0_151]
	at org.elasticsearch.bootstrap.Security.ensureDirectoryExists(Security.java:407) ~[elasticsearch-6.0.1.jar:6.0.1]
	at org.elasticsearch.bootstrap.FilePermissionUtils.addDirectoryPath(FilePermissionUtils.java:68) ~[elasticsearch-6.0.1.jar:6.0.1]
	at org.elasticsearch.bootstrap.Security.addFilePermissions(Security.java:286) ~[elasticsearch-6.0.1.jar:6.0.1]
	at org.elasticsearch.bootstrap.Security.createPermissions(Security.java:248) ~[elasticsearch-6.0.1.jar:6.0.1]
	at org.elasticsearch.bootstrap.Security.configure(Security.java:121) ~[elasticsearch-6.0.1.jar:6.0.1]
	at org.elasticsearch.bootstrap.Bootstrap.setup(Bootstrap.java:207) ~[elasticsearch-6.0.1.jar:6.0.1]
	at org.elasticsearch.bootstrap.Bootstrap.init(Bootstrap.java:322) ~[elasticsearch-6.0.1.jar:6.0.1]
	at org.elasticsearch.bootstrap.Elasticsearch.init(Elasticsearch.java:130) ~[elasticsearch-6.0.1.jar:6.0.1]
```

**Comment by wstrange** [comment]
I see the elasticsearch user does have a gid of 1000.

I think this is a minikube hostpath provisioner issues. Possibly related to 
https://github.com/kubernetes/minikube/issues/956 
https://github.com/kubernetes/kubernetes/issues/2630

**Comment by mikn** [comment]
Hi! I think this may be related to this line: https://github.com/lalamove/helm-elasticsearch/blob/master/templates/_helpers.tpl#L91 and the fact that it is only executed on plugin installs (so if you have no plugins, the permissions won't be changed)

**Comment by mikn** [comment]
Please try with the updated chart now and see if it works!

**Comment by wstrange** [comment]
Indeed - that gets me past that error.

I am seeing a different issue now. The data / master nodes never enter into a ready state. 

```
not enough master nodes discovered during pinging (found [[]], but needed [1]), pinging again
[2018-01-03T19:45:59,652][INFO ][o.e.n.Node               ] [es-elasticsearch-data-0] stopped
[2018-01-03T19:45:59,655][INFO ][o.e.n.Node               ] [es-elasticsearch-data-0] closing ...
[2018-01-03T19:45:59,869][INFO ][o.e.n.Node               ] [es-elasticsearch-data-0] closed
```

The masters do the same thing (start, timeout, then restart..).  

I'll close this issue - as I think this is a different problem..

**Comment by mikn** [comment]
Hmm. Are you running with HTTP enabled or disabled?

**Comment by wstrange** [comment]
I tried both settings in values.yaml - same result

```
 #enableHTTP: false
  enableHTTP: true
```

**Comment by mikn** [comment]
Can you paste the full values.yaml file that you try installing with? And
do you have any logs from a master node that may explain why it doesn't
pass the readiness probe?

**Comment by wstrange** [comment]
I am using the default values.yaml, with the following changes:
```
--- a/values.yaml
+++ b/values.yaml
@@ -58,9 +58,10 @@ data:
   replicas: 2
   antiAffinity: "soft"
   storage: 12Gi
-  storageClass: "default"
+  storageClass: "standard"
   heapSize: 256m
-  enableHTTP: false
+  #enableHTTP: false
+  enableHTTP: true
   # More info on what this setting does is in the config map. Only change this
   # if you set the cpu limit to over 1 full cpu.
   processors: 1
@@ -83,9 +84,10 @@ master:
   replicas: 3
   antiAffinity: "soft"
   storage: 2Gi
-  storageClass: "default"
+  storageClass: "standard"
   heapSize: 256m
-  enableHTTP: false
+  #enableHTTP: false
+  enableHTTP: true
   # More info on what this setting does is in the config map. Only change this
   # if you set the cpu limit to over 1 full cpu.
   processors: 1
```

**Comment by wstrange** [comment]
Here is the master-0 log output:
```
[2018-01-03T21:14:31,272][INFO ][o.e.n.Node               ] [es-elasticsearch-master-0] initializing ...
[2018-01-03T21:14:31,983][INFO ][o.e.e.NodeEnvironment    ] [es-elasticsearch-master-0] using [1] data paths, mounts [[/storage (/dev/sda1)]], net usable_space [6.4gb], net total_space [16.1gb], types [ext4]
[2018-01-03T21:14:31,999][INFO ][o.e.e.NodeEnvironment    ] [es-elasticsearch-master-0] heap size [247.5mb], compressed ordinary object pointers [true]
[2018-01-03T21:14:32,029][INFO ][o.e.n.Node               ] [es-elasticsearch-master-0] node name [es-elasticsearch-master-0], node ID [zIXmc9i8R9a8wOEy43M5ww]
[2018-01-03T21:14:32,038][INFO ][o.e.n.Node               ] [es-elasticsearch-master-0] version[6.0.1], pid[1], build[601be4a/2017-12-04T09:29:09.525Z], OS[Linux/4.9.13/amd64], JVM[Oracle Corporation/OpenJDK 64-Bit Server VM/1.8.0_151/25.151-b12]
[2018-01-03T21:14:32,038][INFO ][o.e.n.Node               ] [es-elasticsearch-master-0] JVM arguments [-XX:+UseConcMarkSweepGC, -XX:CMSInitiatingOccupancyFraction=75, -XX:+UseCMSInitiatingOccupancyOnly, -XX:+AlwaysPreTouch, -Xss1m, -Djava.awt.headless=true, -Dfile.encoding=UTF-8, -Djna.nosys=true, -XX:-OmitStackTraceInFastThrow, -Dio.netty.noUnsafe=true, -Dio.netty.noKeySetOptimization=true, -Dio.netty.recycler.maxCapacityPerThread=0, -Dlog4j.shutdownHookEnabled=false, -Dlog4j2.disable.jmx=true, -Des.cgroups.hierarchy.override=/, -Djava.net.preferIPv4Stack=true, -Xms256m, -Xmx256m, -Des.path.home=/usr/share/elasticsearch, -Des.path.conf=/usr/share/elasticsearch/config]


[2018-01-03T21:14:40,108][INFO ][o.e.p.PluginsService     ] [es-elasticsearch-master-0] loaded module [aggs-matrix-stats]
[2018-01-03T21:14:40,108][INFO ][o.e.p.PluginsService     ] [es-elasticsearch-master-0] loaded module [analysis-common]
[2018-01-03T21:14:40,108][INFO ][o.e.p.PluginsService     ] [es-elasticsearch-master-0] loaded module [ingest-common]
[2018-01-03T21:14:40,108][INFO ][o.e.p.PluginsService     ] [es-elasticsearch-master-0] loaded module [lang-expression]
[2018-01-03T21:14:40,109][INFO ][o.e.p.PluginsService     ] [es-elasticsearch-master-0] loaded module [lang-mustache]
[2018-01-03T21:14:40,109][INFO ][o.e.p.PluginsService     ] [es-elasticsearch-master-0] loaded module [lang-painless]
[2018-01-03T21:14:40,110][INFO ][o.e.p.PluginsService     ] [es-elasticsearch-master-0] loaded module [parent-join]
[2018-01-03T21:14:40,110][INFO ][o.e.p.PluginsService     ] [es-elasticsearch-master-0] loaded module [percolator]
[2018-01-03T21:14:40,110][INFO ][o.e.p.PluginsService     ] [es-elasticsearch-master-0] loaded module [reindex]
[2018-01-03T21:14:40,110][INFO ][o.e.p.PluginsService     ] [es-elasticsearch-master-0] loaded module [repository-url]
[2018-01-03T21:14:40,111][INFO ][o.e.p.PluginsService     ] [es-elasticsearch-master-0] loaded module [transport-netty4]
[2018-01-03T21:14:40,111][INFO ][o.e.p.PluginsService     ] [es-elasticsearch-master-0] loaded module [tribe]
[2018-01-03T21:14:40,113][INFO ][o.e.p.PluginsService     ] [es-elasticsearch-master-0] no plugins loaded
[2018-01-03T21:14:51,683][INFO ][o.e.d.DiscoveryModule    ] [es-elasticsearch-master-0] using discovery type [zen]
[2018-01-03T21:14:56,645][INFO ][o.e.n.Node               ] [es-elasticsearch-master-0] initialized
[2018-01-03T21:14:56,647][INFO ][o.e.n.Node               ] [es-elasticsearch-master-0] starting ...
[2018-01-03T21:14:57,163][INFO ][o.e.t.TransportService   ] [es-elasticsearch-master-0] publish_address {127.0.0.1:9300}, bound_addresses {127.0.0.1:9300}
[2018-01-03T21:15:00,296][INFO ][o.e.c.s.MasterService    ] [es-elasticsearch-master-0] zen-disco-elected-as-master ([0] nodes joined), reason: new_master {es-elasticsearch-master-0}{zIXmc9i8R9a8wOEy43M5ww}{slonr-zgQ0CXouRDb-QuIQ}{127.0.0.1}{127.0.0.1:9300}
[2018-01-03T21:15:00,302][INFO ][o.e.c.s.ClusterApplierService] [es-elasticsearch-master-0] new_master {es-elasticsearch-master-0}{zIXmc9i8R9a8wOEy43M5ww}{slonr-zgQ0CXouRDb-QuIQ}{127.0.0.1}{127.0.0.1:9300}, reason: apply cluster state (from master [master {es-elasticsearch-master-0}{zIXmc9i8R9a8wOEy43M5ww}{slonr-zgQ0CXouRDb-QuIQ}{127.0.0.1}{127.0.0.1:9300} committed version [1] source [zen-disco-elected-as-master ([0] nodes joined)]])
[2018-01-03T21:15:00,341][INFO ][o.e.g.GatewayService     ] [es-elasticsearch-master-0] recovered [0] indices into cluster_state
[2018-01-03T21:15:00,343][INFO ][o.e.h.n.Netty4HttpServerTransport] [es-elasticsearch-master-0] publish_address {127.0.0.1:9200}, bound_addresses {127.0.0.1:9200}
[2018-01-03T21:15:00,343][INFO ][o.e.n.Node               ] [es-elasticsearch-master-0] started
[2018-01-03T21:15:49,312][INFO ][o.e.n.Node               ] [es-elasticsearch-master-0] stopping ...
[2018-01-03T21:15:49,443][INFO ][o.e.n.Node               ] [es-elasticsearch-master-0] stopped
[2018-01-03T21:15:49,446][INFO ][o.e.n.Node               ] [es-elasticsearch-master-0] closing ...
[2018-01-03T21:15:49,560][INFO ][o.e.n.Node               ] [es-elasticsearch-master-0] closed

```

Describing the pod, the readiness probe fails:

```
 Warning  Unhealthy              1m                kubelet, minikube  Liveness probe failed: dial tcp 172.17.0.15:9300: getsockopt: connection refused
  Warning  Unhealthy              1m (x11 over 1m)  kubelet, minikube  Readiness probe failed: Get http://172.17.0.15:9200/_cluster/health?local=true: dial tcp 172.17.0.15:9200: getsockopt: connection refused
```

**Comment by mikn** [comment]
Ah. You need to uncomment the `NETWORK_HOST` variable found here:
```yaml
  env:
    CLUSTER_NAME: "elasticsearch"
    # Uncomment this if you get the "No up-and-running site-local (private)
    # addresses" error.
    # NETWORK_HOST: "_eth0_"
```
This may now be a necessary setting since more recent versions of Elasticsearch, could you report back if this fixes your issue?

**Comment by wstrange** [comment]
@mikn That seems to have done the trick. All the pods now come up to the ready state and look stable. 

Thanks!
