### ISSUE TITLE
Elasticsearch Pod Error

### ISSUE THREAD

**Issue by gromit6891** [lalamove/helm-elasticsearch#33]
When deploying as is to Minikube v.0.25.0  using Kubectl 1.9.0 & Helm 2.10.0 I'm getting the following error from the Elasticsearch pods:
```
Exception in thread "main" ElasticsearchParseException[null-valued setting found for key [cluster.name] found at line number [2], column number [8]]
        at org.elasticsearch.common.settings.Settings.validateValue(Settings.java:759)
        at org.elasticsearch.common.settings.Settings.fromXContent(Settings.java:723)
        at org.elasticsearch.common.settings.Settings.fromXContent(Settings.java:704)
        at org.elasticsearch.common.settings.Settings.fromXContent(Settings.java:673)
        at org.elasticsearch.common.settings.Settings.access$500(Settings.java:82)
        at org.elasticsearch.common.settings.Settings$Builder.loadFromStream(Settings.java:1183)
        at org.elasticsearch.common.settings.Settings$Builder.loadFromPath(Settings.java:1162)
        at org.elasticsearch.node.InternalSettingsPreparer.prepareEnvironment(InternalSettingsPreparer.java:99)
        at org.elasticsearch.cli.EnvironmentAwareCommand.createEnv(EnvironmentAwareCommand.java:95)
        at org.elasticsearch.cli.EnvironmentAwareCommand.execute(EnvironmentAwareCommand.java:86)
        at org.elasticsearch.cli.Command.mainWithoutErrorHandling(Command.java:124)
        at org.elasticsearch.cli.MultiCommand.execute(MultiCommand.java:75)
        at org.elasticsearch.cli.Command.mainWithoutErrorHandling(Command.java:124)
        at org.elasticsearch.cli.Command.main(Command.java:90)
        at org.elasticsearch.plugins.PluginCli.main(PluginCli.java:48)
```
I tried adding a cluster name into the values.yaml file under 'config' but still get the same error.

**Comment by IvanBiv** [comment]
The same!

**Comment by mikn** [comment]
Will investigate! What version of Elasticsearch are you using?

**Comment by IvanBiv** [comment]
ES version 6.2.3 by default from values.yaml

**Comment by bryse-dev** [comment]
in values.yaml, you need to add common.env.CLUSTER_NAME = 'clustername'
